import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

// Mirrors @10play/tentap-editor's own build step: the built HTML is embedded
// as a plain string constant, so react-native-webview can load it via
// `source={{ html: editorHtml }}` with zero runtime fetching — the whole
// editor ships inside the RN JS bundle itself.
const distDir = fileURLToPath(new URL("../dist", import.meta.url));
const html = readFileSync(`${distDir}/index.html`, "utf8");

writeFileSync(
    `${distDir}/editorHtml.js`,
    `// Generated by scripts/stringifyHtml.js — do not edit by hand.\nexport const editorHtml = ${JSON.stringify(html)};\n`,
);

writeFileSync(`${distDir}/editorHtml.d.ts`, "export declare const editorHtml: string;\n");

console.log("Built editor HTML bundle.");
